services:

  postgres:
    profiles: [dev]

  rabbitmq:
    profiles: [dev]

  redis:
    profiles: [dev]

  keycloak:
    profiles: [dev]

  transaction-service:
    profiles: ["container"]

  report-service:
    profiles: ["container"]

  gateway-service:
    profiles: ["container"]
