services:
  postgres:
    image: postgres:17-alpine
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - finance_network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: finance-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - finance_network
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HEALTH_ENABLED: "true"
    command: start-dev --import-realm
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/import/finance-tracker-realm-realm.json:/opt/keycloak/data/import/finance-tracker-realm-realm.json
    networks:
      - finance_network

  gateway-service:
    build:
      context: .
      dockerfile: ./gateway-service/Dockerfile
    container_name: gateway-service
    environment:
      KEYCLOAK_REALM: finance-tracker-realm
      KEYCLOAK_PUBLIC_URL: http://localhost:8080
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/finance-tracker-realm
      KEYCLOAK_SWAGGER_CLIENT_ID: gateway-swagger
    depends_on:
      keycloak:
        condition: service_started
      transaction-service:
        condition: service_healthy
      report-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - finance_network

  transaction-service:
    build:
      context: .
      dockerfile: ./transaction-service/Dockerfile
    container_name: transaction-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8280:8280"
    networks:
      - finance_network

  report-service:
    build:
      context: .
      dockerfile: ./report-service/Dockerfile
    container_name: report-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8380:8380"
    networks:
      - finance_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  finance_network:
    driver: bridge
