services:
  report-service:
    image: ghcr.io/vitorhugo-java/report-service:latest
    ports: !reset []
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  transaction-service:
    image: ghcr.io/vitorhugo-java/transaction-service:latest
    ports: !reset []
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  gateway-service:
    image: ghcr.io/vitorhugo-java/gateway-service:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  keycloak:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  prometheus:
    ports: !reset []

  loki:
    ports: !reset []

  tempo:
    ports: !reset []

  grafana:
