services:
  transaction-service:
    build: off
    ports: !reset []

  report-service:
    build: off
    ports: !reset []

  gateway-service:
    build: off
    ports: !reset []

  keycloak:
    ports:
      - "8180:8080"

  postgres:
    profiles:
      - dev

  finance-mq:
    profiles:
      - dev
