spring:
  application:
    name: transaction-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

  server:
    port: 8081